[env]
'_'.file = { path = ".env" }

FORCE_COLOR = "3"
FULLNAME = "Valentin Panchenko"
EMAIL = "senior.konung@gmail.com"
GPGID = "425C78F2BA2BBAA7"
OH_MY_REPO = "{{config_root}}"

[tools]
deno = "latest"

[tasks]
"setup:gpg" = "./scripts/setup/gpg-setup.ts"
"setup:ssh" = "./scripts/setup/ssh-setup.ts"
"setup:packages" = "./scripts/setup/zsh-setup.ts"
"setup:kitty" = "./scripts/setup/kitty-setup.ts"
"setup:git" = "./scripts/setup/git-setup.ts"
"setup:docker" = "./scripts/setup/docker-setup.ts"
"setup:mise" = "./scripts/setup/mise-setup.ts"
"setup:rclone" = "./scripts/setup/rclone-setup.ts"
"setup:watchman" = "./scripts/setup/watchman-setup.ts"
"setup:zsh" = "./scripts/setup/zsh-setup.ts"
"setup:keyboard" = "./scripts/setup/keyboard-setup.ts"

[tasks.setup]
run = [
    "mise run setup:gpg",
    "mise run setup:ssh",
    "mise run setup:packages",
    "mise run setup:keyboard",
    "mise run setup:git",
    "mise run setup:zsh",
    "mise run setup:kitty",
    "mise run setup:docker",
    "mise run setup:mise",
    "mise run setup:rclone",
    "mise run setup:watchman"
]

[tasks.t]
env.TODOIST_API_KEY = { redact = true, required = true }
env.TODOIST_PROJECTS = { required = true }
run = "./scripts/todoist-group-tasks.ts"