- name: Проверить наличие docker
  ansible.builtin.command: docker -v
  register: docker_check
  failed_when: false
  changed_when: false

- name: Добавить официальный GPG-ключ Docker
  become: true
  ansible.builtin.shell:
    cmd: |
      set -o pipefail &&
      install -m 0755 -d /etc/apt/keyrings &&
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc &&
      chmod a+r /etc/apt/keyrings/docker.asc
    executable: /bin/bash
    creates: /etc/apt/keyrings/docker.asc
  when: docker_check.rc != 0
  changed_when: true

- name: Добавить репозиторий Docker
  become: true
  ansible.builtin.shell:
    cmd: |
      set -o pipefail &&
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" |
      tee /etc/apt/sources.list.d/docker.list >/dev/null
    executable: /bin/bash
    creates: /etc/apt/sources.list.d/docker.list
  when: docker_check.rc != 0
  changed_when: true

- name: Установить Docker Engine
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
  when: docker_check.rc != 0
