- name: Загрузить архив с rclone
  ansible.builtin.get_url:
    url: https://downloads.rclone.org/rclone-current-linux-amd64.zip
    dest: /tmp/rclone.zip
    mode: '0644'

- name: Распаковать архив
  ansible.builtin.unarchive:
    src: /tmp/rclone.zip
    dest: /tmp

- name: Получить путь к распакованной директории
  ansible.builtin.find:
    paths: /tmp
    patterns: rclone-*-linux-amd64
    file_type: directory
  register: found_dir

- name: Переместить исполняемый файл rclone в .local/bin
  ansible.builtin.copy:
    src: '{{ found_dir.files[0].path }}/rclone'
    dest: '{{ paths.localbin }}/'
    directory_mode: '0755'
    mode: '755'
  register: rclone_bin

- name: Получить путь к файлу конфигурации rclone
  ansible.builtin.command: rclone config file
  changed_when: true
  register: rclone_config_file

- name: Сохранить путь к конфигу rclone в переменную
  ansible.builtin.set_fact:
    rclone_config_path: '{{ rclone_config_file.stdout_lines[1] }}'

- name: Загрузить конфигурацию
  ansible.builtin.command: 'gpg -d -q {{ paths.ohmyrepo }}/secrets/rclone-conf.secret'
  register: rclone_config
  changed_when: false

- name: Скопировать конфигурацию rclone
  ansible.builtin.copy:
    content: '{{ rclone_config.stdout }}'
    dest: '{{ rclone_config_path }}'
    mode: '0644'

- name: Создать директорию для монтирования Google Drive
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/gdrive'
    state: directory
    mode: '0755'

- name: Создать директорию для systemd user units
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.config/systemd/user'
    state: directory
    mode: '0755'

- name: Создать systemd unit для rclone
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Mounting google drive using rclone
      After=default.target

      [Service]
      ExecStart={{ rclone_bin.dest }} mount senior.konung: {{ ansible_env.HOME }}/gdrive
      ExecStop=umount -l {{ ansible_env.HOME }}/gdrive

      [Install]
      WantedBy=default.target
    dest: '{{ ansible_env.HOME }}/.config/systemd/user/rclone-google-drive.service'
    mode: '0644'

- name: Перезагрузить systemd user units
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Включить автозапуск rclone-google-drive.service
  ansible.builtin.systemd:
    name: rclone-google-drive.service
    enabled: true
    scope: user

- name: Запустить rclone-google-drive.service
  ansible.builtin.systemd:
    name: rclone-google-drive.service
    state: started
    scope: user
