- name: Получить данные о последней версии Watchman
  ansible.builtin.uri:
    url: "https://api.github.com/repos/facebook/watchman/releases/latest"
    method: GET
    return_content: true
  register: api_response

- name: Скачать архив с Watchman
  ansible.builtin.get_url:
    url: "{{ api_response.json.assets[0].browser_download_url }}"
    dest: "/tmp/watchman.tar.gz"
    mode: '0644'

- name: Распаковать архив с Watchman
  ansible.builtin.unarchive:
    src: "/tmp/watchman.tar.gz"
    dest: "/tmp"

- name: Получить путь к распакованной директории
  ansible.builtin.find:
    paths: /tmp
    patterns: watchman-*-linux
    file_type: directory
  register: found_dir

- name: Переместить и переименовать директорию Watchman
  ansible.builtin.command:
    cmd: "mv {{ found_dir.files[0].path }} {{ ansible_env.HOME }}/.local/watchman"
    creates: "{{ ansible_env.HOME }}/.local/watchman"

- name: Создать все необходимые директории для Watchman
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "/usr/local/bin"
    - "/usr/local/lib"
    - "/usr/local/var/run/watchman"

- name: Создать символические ссылки на исполняемые файлы Watchman
  become: true
  ansible.builtin.command: "cp -rsf {{ ansible_env.HOME }}/.local/watchman/bin/. /usr/local/bin"
  changed_when: true

- name: Создать символические ссылки на библиотечные файлы Watchman
  become: true
  ansible.builtin.command: "cp -rsf {{ ansible_env.HOME }}/.local/watchman/lib/. /usr/local/lib"
  changed_when: true

- name: Чтобы не было ошибок используем системный liblzma.so
  become: true
  ansible.builtin.file:
    src: "/usr/lib/x86_64-linux-gnu/liblzma.so.5"
    dest: "/usr/local/lib/liblzma.so.5"
    state: link
    force: true

- name: Изменить права на директорию /usr/local/var/run/watchman
  become: true
  ansible.builtin.file:
    path: "/usr/local/var/run/watchman"
    mode: '2777'

- name: Изменить права на исполняемый файл watchman
  become: true
  ansible.builtin.file:
    path: "/usr/local/bin/watchman"
    mode: '755'
