# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json

backend: auto
auto_restart: true
clipboard_threshold: 100
restore_clipboard_delay: 300
