# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json

filter_class: kitty
backend: inject
disable_x11_fast_inject: true
extra_includes:
  - ../match/_terminal.yml
