# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json

filter_title: Visual Studio Code
backend: clipboard
extra_includes:
  - ../match/_ts_snippets.yml
